package org.kie.example.traffic.traffic_violation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String propertyDetails;

	private java.lang.String result;

	private java.lang.String transactionDetails;

	private java.lang.String concessionType;

	private java.lang.Integer transferees;

	public FormData() {
	}

	public java.lang.String getPropertyDetails() {
		return this.propertyDetails;
	}

	public void setPropertyDetails(java.lang.String propertyDetails) {
		this.propertyDetails = propertyDetails;
	}

	public String toString() {
		return this.propertyDetails;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.String getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(java.lang.String transactionDetails) {
		this.transactionDetails = transactionDetails;
	}

	public java.lang.String getConcessionType() {
		return this.concessionType;
	}

	public void setConcessionType(java.lang.String concessionType) {
		this.concessionType = concessionType;
	}

	public java.lang.Integer getTransferees() {
		return this.transferees;
	}

	public void setTransferees(java.lang.Integer transferees) {
		this.transferees = transferees;
	}

	public FormData(java.lang.String propertyDetails, java.lang.String result,
			java.lang.String transactionDetails,
			java.lang.String concessionType, java.lang.Integer transferees) {
		this.propertyDetails = propertyDetails;
		this.result = result;
		this.transactionDetails = transactionDetails;
		this.concessionType = concessionType;
		this.transferees = transferees;
	}

}