package org.kie.example.traffic.traffic_violation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String transactionType;

	private java.lang.Integer purchasePrice;

	private java.lang.String purchaserType;

	public FormData() {
	}

	public String toString() {
		return this.propertyDetails;
	}

	public java.lang.String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(java.lang.String transactionType) {
		this.transactionType = transactionType;
	}

	public java.lang.Integer getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(java.lang.Integer purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	public java.lang.String getPurchaserType() {
		return this.purchaserType;
	}

	public void setPurchaserType(java.lang.String purchaserType) {
		this.purchaserType = purchaserType;
	}

	public FormData(java.lang.String transactionType,
			java.lang.Integer purchasePrice, java.lang.String purchaserType) {
		this.transactionType = transactionType;
		this.purchasePrice = purchasePrice;
		this.purchaserType = purchaserType;
	}

}